#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
  herbstclient "$@"
}

floaterm="myhc float"
polyreload="$HOME/.config/herbstluftwm/polybar-start"
mastervolup="pamixer -i 5"
mastervoldn="pamixer -d 5"
mastervolmu="pamixer -t"
mastervoldm="vdim"
# spotifydvolup="appvol spotifyd -n +5"
# spotifydvoldn="appvol spotifyd -n -5"
# spotifydtoggle="playerctl -p spotifyd play-pause"
# spotifydnext="playerctl -p spotifyd next"
# spotifydprev="playerctl -p spotifyd previous"
rofiw="rofi -show window"

hc emit_hook reload

fn="$(xgetres dmenu.font)"
nb="$(xgetres color0)"
nf="$(xgetres color7)"
sb="$(xgetres color9)"
sf="$(xgetres color0)"

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-x           spawn dmenu_run -fn "$fn" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf"
hc keybind $Mod-Control-x   spawn bmenu
hc keybind $Mod-Shift-e     spawn hc-restart-menu

# shellcheck disable=SC2086
{

# floating terminal
hc keybind $Mod-a           spawn $floaterm

# polybar reload
hc keybind $Mod-Control-r   spawn $polyreload

# mpd
hc keybind $Mod-F1          spawn p
hc keybind $Mod-Shift-F1    spawn pla
hc keybind $Mod-F2          spawn pv
hc keybind $Mod-F3          spawn nx
hc keybind $Mod-F4          spawn s
hc keybind $Mod-Shift-F4    spawn sta -n
hc keybind $Mod-Shift-F12   spawn dim -n
hc keybind $Mod-F10         spawn vol -n -5
hc keybind $Mod-F11         spawn vol -n +5

# spotifyd
# hc keybind $Mod-F5          spawn $spotifydtoggle
# hc keybind $Mod-F6          spawn $spotifydprev
# hc keybind $Mod-F7          spawn $spotifydnext
# hc keybind $Mod-Shift-F10   spawn $spotifydvoldn
# hc keybind $Mod-Shift-F11   spawn $spotifydvolup

# master volume
hc keybind $Mod-Control-F9  spawn $mastervolmu
hc keybind $Mod-Control-F10 spawn $mastervoldn
hc keybind $Mod-Control-F11 spawn $mastervolup
hc keybind $Mod-Control-F12 spawn $mastervoldm

# utils
hc keybind $Mod-Control-p   spawn getpass
hc keybind $Mod-Control-w   spawn light
hc keybind $Mod-Shift-a     spawn $rofiw
}

hc keybind $Mod-Control-e   spawn emojis
hc keybind $Mod-Control-q   quit
hc keybind $Mod-Shift-r     reload
hc keybind $Mod-Shift-q     close
hc keybind $Mod-Return      spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback

# dunst
hc keybind Control-space    spawn dunstctl close
hc keybind Control-Shift-space  spawn dunstctl close-all
hc keybind Control-Shift-h  spawn dunstctl history-pop

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
# tag_names=( {1..9} )
# tag_keys=( {1..9} 0 )

# hc rename default "${tag_names[0]}" || true
# for i in "${!tag_names[@]}" ; do
  # hc add "${tag_names[$i]}"
  # key="${tag_keys[$i]}"
  # if [ -n "$key" ] ; then
    # hc keybind "$Mod-$key" use_index "$i"
    # hc keybind "$Mod-$key" move_index "$i"
  # fi
# done

# cycle through tags
hc keybind $Mod-asterisk use_index +1 --skip-visible
hc keybind $Mod-ugrave   use_index -1 --skip-visible

hc set swap_monitors_to_get_tag false

hc rename default 0 || true

for ((i=1; i<7; i++)); do hc add $((i)); done

hc rename 0 def
hc rename 1 www
hc rename 2 mon
hc rename 3 srv
hc rename 4 dev
hc rename 5 oth
hc rename 6 mus

hc keybind $Mod-ampersand  spawn myhc switch_to_tag 0
hc keybind $Mod-eacute     spawn myhc switch_to_tag 1
hc keybind $Mod-quotedbl   spawn myhc switch_to_tag 2
hc keybind $Mod-apostrophe spawn myhc switch_to_tag 3
hc keybind $Mod-parenleft  spawn myhc switch_to_tag 4
hc keybind $Mod-minus      spawn myhc switch_to_tag 5
hc keybind $Mod-egrave     spawn myhc switch_to_tag 6
hc keybind $Mod-underscore spawn myhc switch_to_tag 7
hc keybind $Mod-ccedilla   spawn myhc switch_to_tag 8

hc keybind $Mod-Control-ampersand  spawn myhc switch_to_monitor 0
hc keybind $Mod-Control-eacute     spawn myhc switch_to_monitor 1
hc keybind $Mod-Control-quotedbl   spawn myhc switch_to_monitor 2
hc keybind $Mod-Control-apostrophe spawn myhc switch_to_monitor 3
hc keybind $Mod-Control-parenleft  spawn myhc switch_to_monitor 4
hc keybind $Mod-Control-minus      spawn myhc switch_to_monitor 5
hc keybind $Mod-Control-egrave     spawn myhc switch_to_monitor 6
hc keybind $Mod-Control-underscore spawn myhc switch_to_monitor 7
hc keybind $Mod-Control-ccedilla   spawn myhc switch_to_monitor 8

hc keybind $Mod-Shift-ampersand  move_index 0
hc keybind $Mod-Shift-eacute     move_index 1
hc keybind $Mod-Shift-quotedbl   move_index 2
hc keybind $Mod-Shift-apostrophe move_index 3
hc keybind $Mod-Shift-parenleft  move_index 4
hc keybind $Mod-Shift-minus      move_index 5
hc keybind $Mod-Shift-egrave     move_index 6
hc keybind $Mod-Shift-underscore move_index 7
hc keybind $Mod-Shift-ccedilla   move_index 8

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s spawn myhc setlayout f # floating
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle

hc keybind $Mod-v spawn myhc setlayout v # vertical
hc keybind $Mod-w spawn myhc setlayout h # horizontal
hc keybind $Mod-m spawn myhc setlayout m # max
hc keybind $Mod-g spawn myhc setlayout g # grid

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
# hc keybind $Mod-space                                         \
   # or , and . compare tags.focus.curframe_wcount = 2          \
   # . cycle_layout +1 vertical horizontal max vertical grid    \
   # , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-twosuperior cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i spawn myhc jump_to_urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color "$(xgetres color7)"
hc set frame_border_normal_color "$(xgetres color0)"
hc set frame_bg_normal_color "$(xgetres color0)"
hc set frame_bg_active_color "$(xgetres color3)"
hc set frame_border_width 1
hc set always_show_frame off
hc set frame_bg_transparent on
hc set frame_transparent_width 1
hc set frame_gap 1

hc attr theme.active.color "$(xgetres color6)"
hc attr theme.normal.color "$(xgetres color0)"
hc attr theme.urgent.color "$(xgetres color3)"
hc attr theme.inner_width 1
hc attr theme.inner_color "$(xgetres color0)"
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color "$(xgetres color0)"
hc attr theme.active.inner_color "$(xgetres color7)"
hc attr theme.active.outer_color "$(xgetres color7)"
hc attr theme.background_color "$(xgetres color2)"

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings on
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on manage=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class=mpv         tag=def
hc rule class=qutebrowser tag=www
hc rule class=firefox     tag=www
hc rule class=lagrange    tag=www
hc rule class=Steam       tag=oth

hc rule instance="vkeybd.tcl" floating=on focus=on
hc rule instance="qjackctl" floating=on focus=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
hc set_monitors 1920x1080+0+0 1366x768+1920+312

# launch polybar
"$HOME/.config/herbstluftwm/polybar-start"
