#! /usr/bin/env bash

spkfile="$HOME/.config/speaker"
volfile="${spkfile}.volume"

get_status() {
  unset btalias btstate
  while read -r info; do
    [[ $info =~ ^power:[[:space:]](.+)$ ]] &&
      if [[ ${BASH_REMATCH[1]} == "on" ]]; then
        btstate=""
      else
        btstate=""
      fi
    [[ $info =~ ^device:[[:space:]](.+)$ ]] \
       && btalias="${BASH_REMATCH[1]}"
  done < <(btspk s)
}

show_device() {
  get_status
  if [[ -s "$volfile" ]]; then dim=""; else unset dim; fi
  echo "${btstate} ${btalias:-Amp} $dim"
}

quit() {
  echo "×"
  exit
}

[[ -a "$spkfile" ]] || :> "$spkfile"

trap quit INT QUIT TERM

show_device

while read -r; do
  show_device
done < <(entr -n -p date <<< "$spkfile" & entr -n -p date <<< "$volfile")

