#! /usr/bin/env bash
#
# Utility to listen to Yeelight bulb
#   

read_value() {
  local param="$1"
  local value
  for line in "${_st[@]}"; do
    if [[ $line =~ ^$param:.*$ ]]; then
      value="${line//$param:/}"
      # shellcheck disable=SC2086
      # this prints value without leading whitespaces
      echo $value
      return 0
    fi
  done
  return 1
}

get_status() {
  local W B T S

  IFS=$'\n' read -d "" -ra _st <<< "$(ylightc -s)"

  H=$(read_value host)
  P=$(read_value port)
  W=$(read_value power)
  B=$(read_value brightness)
  T=$(read_value timer)

  if [[ $W ]]; then
  	[[ $W == "on" ]] && S="->- $B" || S="-/-"
  	[[ $T ]] && S+="  $T"
  else
  	S="-?-"
  fi

  # maxlen=16
  printf "%-14s\n" "$S"
}

listen() {
  while read -r; do
  	get_status
  done < <(netcat "$H" "$P" 2> /dev/null || exit 127)
}

quit() {
  local S="×"
  printf "%-16s\n" "$S"
  #shellcheck disable=SC2046
  kill $(lscp $$) 2> /dev/null
  exit 0
}

trap quit INT TERM QUIT
get_status
while :; do
  listen
  (($?==127)) && continue
  break
done
